# Generated by Django 2.2.19 on 2021-12-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voditeli',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(verbose_name='Имя')),
                ('Sure_name', models.TextField(verbose_name='Фамилия')),
                ('Date_of_birth', models.TextField(verbose_name='Дата рождения')),
                ('number', models.IntegerField(verbose_name='Номер телефона')),
                ('Created', models.DateTimeField(auto_now=True, verbose_name='Дата регистрации')),
                ('Auto', models.TextField(verbose_name='Автомобиль')),
                ('Auto_number', models.TextField(verbose_name='госномер')),
            ],
        ),
        migrations.DeleteModel(
            name='Taxist',
        ),
    ]
