# Generated by Django 2.2.19 on 2021-12-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20211207_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voditeli',
            name='Auto_number',
            field=models.IntegerField(verbose_name='госномер'),
        ),
        migrations.AlterField(
            model_name='voditeli',
            name='Date_of_birth',
            field=models.IntegerField(verbose_name='Дата рождения'),
        ),
    ]
