# Generated by Django 2.2.19 on 2021-12-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20211207_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voditeli',
            name='Auto',
            field=models.TextField(max_length=10, verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='voditeli',
            name='Auto_number',
            field=models.CharField(max_length=10, verbose_name='госномер'),
        ),
        migrations.AlterField(
            model_name='voditeli',
            name='Date_of_birth',
            field=models.CharField(max_length=10, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='voditeli',
            name='Name',
            field=models.CharField(max_length=10, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='voditeli',
            name='Sure_name',
            field=models.CharField(max_length=15, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='voditeli',
            name='number',
            field=models.CharField(max_length=15, verbose_name='Номер телефона'),
        ),
    ]
