# Generated by Django 2.2.19 on 2021-12-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20211207_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voditeli',
            name='Auto',
            field=models.TextField(max_length=20, verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='voditeli',
            name='Name',
            field=models.CharField(max_length=15, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='voditeli',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
    ]
