# Generated by Django 2.2.19 on 2021-12-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20211207_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voditeli',
            options={'ordering': ['id']},
        ),
    ]
