# Generated by Django 2.2.19 on 2021-12-08 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20211207_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voditeli',
            options={'ordering': ('id',)},
        ),
    ]
