# Generated by Django 2.2.19 on 2021-12-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispetchery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15, verbose_name='Имя')),
                ('Sure_name', models.CharField(max_length=15, verbose_name='Фамилия')),
                ('Date_of_birth', models.CharField(max_length=10, verbose_name='Номер телефона')),
                ('Number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('Created', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('Email', models.EmailField(max_length=254, verbose_name='email')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
