# Generated by Django 2.2.19 on 2021-12-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_dispetchery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispetchery',
            name='Date_of_birth',
            field=models.CharField(max_length=10, verbose_name='Дата рождения'),
        ),
    ]
