# Generated by Django 2.2.19 on 2021-12-21 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_dispetchery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='Name',
            new_name='Name_man',
        ),
        migrations.RenameField(
            model_name='voditeli',
            old_name='Name',
            new_name='Name_vod',
        ),
        migrations.AlterField(
            model_name='dispetchery',
            name='Date_of_birth',
            field=models.CharField(max_length=10, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='voditeli',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('Marshrut', models.CharField(max_length=30, verbose_name='Маршрут')),
                ('Status', models.CharField(max_length=15, verbose_name='Статус')),
                ('Order_number', models.CharField(max_length=15, verbose_name='Номер заказа')),
                ('Name_man', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='backend.People')),
                ('Name_vod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='backend.Voditeli')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
