# Generated by Django 2.2.19 on 2021-12-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20211215_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voditeli',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
    ]
