# Generated by Django 2.2.19 on 2021-12-22 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20211222_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Name_vod',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='Name',
            new_name='Name_man',
        ),
        migrations.RenameField(
            model_name='voditeli',
            old_name='Name',
            new_name='Name_vod',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Name_man',
        ),
    ]
