# Generated by Django 2.2.19 on 2021-12-22 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20211222_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Name',
            new_name='Name_vodil',
        ),
        migrations.AddField(
            model_name='order',
            name='Name_people',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='backend.People'),
        ),
    ]
