# Generated by Django 2.2.19 on 2021-12-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20211222_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Name_people',
        ),
        migrations.AddField(
            model_name='order',
            name='Name_people',
            field=models.ManyToManyField(to='backend.People'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='Name_vodil',
        ),
        migrations.AddField(
            model_name='order',
            name='Name_vodil',
            field=models.ManyToManyField(to='backend.Voditeli'),
        ),
    ]
