# Generated by Django 2.2.19 on 2021-12-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20211224_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Name_people',
            field=models.ManyToManyField(related_name='orders', to='backend.People'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Name_vodil',
            field=models.ManyToManyField(related_name='orders', to='backend.Voditeli'),
        ),
    ]
