# Generated by Django 2.2.19 on 2021-12-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20211224_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='Sure_name',
        ),
        migrations.RemoveField(
            model_name='voditeli',
            name='Sure_name',
        ),
        migrations.AlterField(
            model_name='people',
            name='Name_man',
            field=models.CharField(max_length=30, verbose_name='Имя и Фамилия'),
        ),
        migrations.AlterField(
            model_name='voditeli',
            name='Name_vod',
            field=models.CharField(max_length=30, verbose_name='Имя и Фамилия'),
        ),
    ]
